- name: Install node and npm
  become: yes
  hosts: node-dev
  tasks:
  - name: update the repo
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600
  - name: Install node npm
    apt: 
      pkg:
      - nodejs
      - npm
      - unzip



 
