apiVersion: v1
kind: Deployment
metadata:
  name: {{ .values.metadata.name }}
spec:
  replicas: {{ .Values.metadata.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.spec.selector.app }}
  template:
    metadata:
      labels:
        name: {{ .Values.spec.selector.name }}
    spec:
      containers:
      - name: {{ .Values.spec.containers.name }}
      # below image should be changed based on the code was changed
        image: 
        resources:
           requests:
             memory: {{ .Values.spec.containers.resources.requests.memory }}
             cpu: {{ .Values.spec.containers.resources.requests.cpu }}
            limits:
              memory: {{ .Values.spec.containers.resources.requests.limits }}
              cpu: {{ .Values.spec.container.resources.requests.limits }}

              